### ISSUE TITLE
Should not display exit message unless something went wrong

### ISSUE THREAD

**Issue by koranza** [alaviss/nim.nvim#11]
I'm seeing a message printed to the terminal screen when I exit neovim after editing a nim file. The message says "nimsuggest instance for project [projectName] exited with exitcode: [exitcode]"

It would be better imho to only show the message if nimsuggest exited with with a code besides 0/success.

(eg. in file autoload/nim/suggest.vim, check a:data != 0 in OnEvent function)

**Comment by alaviss** [comment]
PRs are welcome :)

**Comment by alaviss** [comment]
The `refactoring` branch currently features this. I might change my mind if it hides away crashed nimsuggest instances however.
