### ISSUE TITLE
nimsuggest exits with errorcode 143

### ISSUE THREAD

**Issue by itmuckel** [alaviss/nim.nvim#16]
* nvim 0.4.2
* Windows 10
* ConEmu, Powershell, GitBash (console doesn't matter; error is the same)
* nim 1.0.2

When I open a nim file there is no autocomplete or anything.
When I close nvim, I see an error output:
```
nimsuggest instance for project C:\Users\blablabla stopped with exitcode: 143
```

**Comment by alaviss** [comment]
This exitcode is rather normal. It's `128 + SIGTERM(15)`, which is basically just neovim sending the termination signal to nimsuggest. I probably should patch nimsuggest to handle this signal.
As for autocomplete, how did you set it up?
