### ISSUE TITLE
Can't install, Please help

### ISSUE THREAD

**Issue by vinodvinu** [alaviss/nim.nvim#19]
Hi, i tried to type this command "plug 'alaviss/nim.nvim' " and hit enter. But it says that--
 "'plug' is not recognized as an internal or external command,
operable program or batch file. "
Please provide detailed information about how to install.

**Comment by belamenso** [comment]
1. Use a newer (>=0.3) version of nvim (installation instructions are here https://github.com/neovim/neovim/wiki/Installing-Neovim).
2. Install Plug (it's a vim/neovim package manager) (instructions here: https://github.com/junegunn/vim-plug#neovim)
3. In your neovim config file (`~/.config/nvim/init.vim` on my machine) add the following (`~/.vim/plugged` is Plug's data directory, you can change it):
```
call plug#begin('~/.vim/plugged')
Plug 'alaviss/nim.nvim'
call plug#end()
```
4. Enter neovim (`nvim`) and type `<ESC>:PlugInstall<ENTER>`

**Comment by vinodvinu** [comment]
@belamenso 
Thanks a lot. Let me try.

**Comment by alaviss** [comment]
@vinodvinu
If everything worked out, please close this issue, thanks!

**Comment by vinodvinu** [comment]
Sure :)
