### ISSUE TITLE
stable version of nimsuggest immediately error-exits

### ISSUE THREAD

**Issue by gemath** [alaviss/nim.nvim#2]
Whenever NeoVim loads a .nim file this error message occurs:

`nimsuggest instance for project <project path> exited with exitCode: 1`

This only happens with the stable version of nimsuggest, with the devel version it all works.

**Comment by alaviss** [comment]
It's stated in the readme that this plugin currently requires the latest development version nimsuggest. This is because the plugin is dependent on nim-lang/nim#10328 which is `devel`-only atm.

**Comment by gemath** [comment]
Ah, sry, to dumb to read :o)

**Comment by FedericoCeratto** [comment]
@alaviss this is happening with the newly released compiler 0.19.6 as well.

**Comment by alaviss** [comment]
This will only be available starting from nim 0.20.0 which is why I wrote "development compiler required".

I think it's possible to do a bit of regex matching to figure out if the current nimsuggest is compatible.

**Comment by FedericoCeratto** [comment]
#5 is related.
@alaviss a simple error message "check if your nimsuggest supports --autobind" can help a lot
