### ISSUE TITLE
Got hightlight but no autocompletion

### ISSUE THREAD

**Issue by 26awen** [alaviss/nim.nvim#26]
Here is my nvim version:
![image](https://user-images.githubusercontent.com/13186663/78552615-64a20f00-783a-11ea-874d-ed3047fe73c7.png)

And here is my ~/.config/nvim/init.vim :
![image](https://user-images.githubusercontent.com/13186663/78552670-78e60c00-783a-11ea-9523-47eaac77e4eb.png)

Please help~. I usually write code with vscode on a win10, but since I switched to a WSL, I think I can only use a neovim (or a vim) editor. But I can not get it done 😭

**Comment by alaviss** [comment]
Can you try triggering the auto-complete (just typing something should do) then check if there's any message when you run `:messages` inside neovim.

**Comment by 26awen** [comment]
@alaviss I can not see any message, btw I can make the completion work on my laptop now, without the preview window working (and still not work on my desktop pc and will try again later)
here is my nimsuggest version (I use the same nim version 1.2 and a ubuntu wsl, the envs on my two PCs are  similar)
![image](https://user-images.githubusercontent.com/13186663/78622777-a1ace680-78b8-11ea-910c-16634d1deab7.png)

**Comment by 26awen** [comment]
update:
I did get some error message on my desktop. 
![image](https://user-images.githubusercontent.com/13186663/78657862-f4f45880-78fb-11ea-8bf0-23ac7f8514da.png)
(I think the "E486" is the old error , since I tried ncm2 once.)
The key message is no nimsuggest is running for this projest
So by now , I can not do anything with nim.nvim on my desktop. 
The autocomplettion is working on my laptop, you can see the imported modules are colored.,  but on my desktop, they are not.

**Comment by alaviss** [comment]
You might want to investigate the ncm2 error. Vimscript have a tendency of screwing everything up after an error.

Additionally, can you check the nimsuggest version on the desktop as well?

> screenshot from my laptop, on which the completion is working, but preview window did not show

Set `g:asyncomplete_auto_completeopt` to `0`. Setting that to `1` prompt asyncomplete to override your `completeopt`.

**Comment by 26awen** [comment]
@alaviss 

> You might want to investigate the ncm2 error. Vimscript have a tendency of screwing everything up after an error.
After I reinstall all the thing on my desktop. The autocompletion works now.

> Set g:asyncomplete_auto_completeopt to 0. Setting that to 1 prompt asyncomplete to override your completeopt.
After I set it to 0, it goes buggy, so I record a video to show it.(BTW after I triggle this bug , I type ":message" and to see nothing)
<script id="asciicast-Wq0hRg7ePWX0f6p7KBEFUGyRx" src="https://asciinema.org/a/Wq0hRg7ePWX0f6p7KBEFUGyRx.js" async></script>

**Comment by alaviss** [comment]
Try this set of configurations:

```vim
set completeopt+=menuone,noselect,preview

let g:asyncomplete_smart_completion = 1
let g:asyncomplete_auto_popup = 1
let g:asyncomplete_auto_completeopt = 0
imap <c-space> <Plug>(asyncomplete_force_refresh)
```

This is what I use myself :)

> After I reinstall all the thing on my desktop. The autocompletion works now.

Glad that works now :)

**Comment by 26awen** [comment]
@alaviss Is works good now. Thanks.

**Comment by alaviss** [comment]
No problem, closing as solved.
