### ISSUE TITLE
E475: Invalid value for argument cmd: 'nimsuggest' is not executable

### ISSUE THREAD

**Issue by lf-araujo** [alaviss/nim.nvim#28]
Hi,

Thank you for this package.

I am currently using the following nvim version:

`NVIM v0.5.0-nightly-6-gef0398f
`

I am not sure when the plugin started giving me the above error, I suppose it was after a snap update. Could you please help me debug this?

The entire error reads:

```
Error detected while processing function nim#suggest#ProjectFindOrStart[4]..nim#
suggest#ProjectStart[1]..nim#suggest#ProjectFileStart[7]..nim#suggest#manager#Ne
wInstance:
line    1:
E475: Invalid value for argument cmd: 'nimsuggest' is not executable
Error detected while processing function nim#suggest#ProjectFindOrStart:
line    4:
E171: Missing :endif

```

**Comment by alaviss** [comment]
This error generally means that `nimsuggest` is not in your `PATH`. You should verify whether the executable can still be located by running `which nimsuggest` on the command line.

**Comment by lf-araujo** [comment]
Thank you,

Yes, I tested this too:


```
› which nimsuggest
/home/luis/.nimble/bin/nimsuggest
```

I am thinking this is a bug due to the snap version I am running, it is possibly not detecting the binary due to the confinement.

**Comment by alaviss** [comment]
Yea, that might be the case. If so then there's not much that I can do.

**Comment by alaviss** [comment]
Closing as this appears to be an issue with Snap isolation. I'd recommend switching to conventional packaging for now, until the issue of interop between isolated software and the outside world gets better.
