### ISSUE TITLE
Personalize syntax highlighting color

### ISSUE THREAD

**Issue by Clonkk** [alaviss/nim.nvim#33]
Hi,

Is there an easy way to personalize which colour are which element (for example I'd like strings to be a different colour than proc, variable to be white by default etc...) or do I have to modify the plugin myself ?

**Comment by alaviss** [comment]
The plugin by default makes use of neovim's highlighting groups (see `:h group-name`). You can customize these groups colors via a colorscheme. The groups you're looking for are: `String`, `Identifier` and `Function`.

If you want finer grained customization (ie. different colors for a proc vs a func), you can customize the highlighting of each nim-specific syntax groups (see [here](https://github.com/alaviss/nim.nvim/blob/master/syntax/nim.vim#L175-L224) for a comprehensive list). No modification to the plugin needed, simply use `:highlight! <group name> <color options>` or `:highlight link <group name> <another group>` (see `:h highlight` for more information) in your colorscheme to override the default color choices.

**Comment by Clonkk** [comment]
Thanks, I'm looking into it !

Also, I don't know if it's on purpose but ìmport stuff` and import stuff/otherstuff` have different color highlighting

**Comment by alaviss** [comment]
> I don't know if it's on purpose but `import stuff` and `import stuff/otherstuff` have different color highlighting.

It's not, `nimsuggest` produces inconsistent highlighting for module names, which unfortunately I can't do much about. You can disable highlighting for module names with `highlight link nimSugModule NONE` if that bothers you :P

> Do you want me to close this since it's technically not an issue ?

If your question is solved, please close the issue :)

**Comment by Clonkk** [comment]
Thanks mate !
