### ISSUE TITLE
Neovim Startup Error

### ISSUE THREAD

**Issue by oliversandli** [alaviss/nim.nvim#34]
When I open any `*.nim` file with neovim, I get this error message:

```
Error detected while processing ~/.local/share/nvim/plugged/nim.nvim/syntax/nim.vim:
line  161:
E15: Invalid expression: . 'start=+\<\%(' .. nim#SearchIdentifierRegex('emit') .. '\|' .. nim#SearchIdentifierRegex('cod
egendecl') .. '\)\m\s*:+ ' .. 'end=+\ze\%(,\|\.\?}\)+ ' .. 'contains=@nimKeywordGroup,@nimLiteralGroup,@nimCommentGroup,
nimPragma,nimEmit.\+ ' .. 'contained'
Press ENTER or type command to continue
```

It sounds like there are some syntax errors in `nim.vim` ?

The errors are far from breaking (syntax highlighting still works, etc.) but I thought you should know about this. Cheers for making this awesome plugin!

**Comment by alaviss** [comment]
That's weird, what version of `neovim` are you running? You can get the info by running `nvim --version`.

**Comment by oliversandli** [comment]
Ahh, I'm running v0.3.4, and the latest is v0.4.4. v0.3.4 is the latest version available on the Debian package repos. I'll do a manual install/upgrade in the morning, see if the error persists. Thx!

**Comment by oliversandli** [comment]
Yep, it works perfectly in v0.4.4 on my Arch box (Debian's `apt-get` for the `neovim` testing branch was being, umm, unhelpful).
