### ISSUE TITLE
Disable error coloring

### ISSUE THREAD

**Issue by vitreo12** [alaviss/nim.nvim#39]
Hi, I found quite annoying to have the "red" highlight before I finish typing a word: is there a way to disable this kind of error checking?

Thanks a lot for this great plugin!

**Comment by alaviss** [comment]
You can do so by adding `highlight link nimSugUnknown NONE` to your colorscheme, which will disable the highlighting for unknown symbols (those red highlights).

For reference, here are the names of the highlighting groups used by the semantic highlighter: https://github.com/alaviss/nim.nvim/blob/master/syntax/nim.vim#L203-L224

**Comment by vitreo12** [comment]
Great! Works like a charm, thanks :)
