### ISSUE TITLE
Neovim stuck a 100% CPU 

### ISSUE THREAD

**Issue by Clonkk** [alaviss/nim.nvim#41]
This is a summary of the discussion of https://github.com/PMunch/nimlsp/issues/77. 

It seems it is related to this plugin instead.

> When opening a Nim file with Neovim, it gets stucks at 100% CPU after the file is opened for a while. Some action (?) will trigger the bug instantly (inserting "{" will do that for instance).

>The bug happpend when opening the file https://github.com/SciNim/flambeau/blob/master/flambeau/raw_bindings/tensors.nim
> Here is what I do that reproduce :
   *  Open tensors.nim
   * Wait around 30 seconds
   * Press "o" (newline + insert mode)
   * Write "{" character

> This is on NVIM v0.5.0-dev+1176-g94381310c2. I'll update to the new nightly NVIM v0.5.0-dev+1227-gb518b9076 and test again but I had the same result with v0.4.3 and v0.4.4.

>  using :set syntax=off or another syntax highlighting plugin solves the issue

**Comment by alaviss** [comment]
I can't reproduce this bug on v0.4.4. Do you have to insert `{` at a specific position?

**Comment by Clonkk** [comment]
I usually do it on a newline.

It doesn't necessarily occurs on the first occurrence but I can generally reproduce it in less than a minute.

**Comment by zetashift** [comment]
I could reproduce it, maybe it has something to do with if you use a lsp-client (in my case nvim-lspconfig) and the syntax highlighting? https://github.com/neovim/nvim-lspconfig

**Comment by Clonkk** [comment]
I tried both neoclide/coc and prabirshrestha/vim-lsp as lsp client and both could reproduce the issue so that's unlikely.

**Comment by zetashift** [comment]
I meant, if alaviss/leorize isn't using a LSP client then that might explain why he can't reproduce it? 
So the bug occurs only if there is an LSP client AND this is used for only highlighting?

**Comment by Clonkk** [comment]
Aye, could be. But that would be a weird interaction then

**Comment by alaviss** [comment]
I figured out what the bug is. It's in the smart indentation plugin and I'm trying to come up with a fix. Thanks for your help.

**Comment by zetashift** [comment]
Thank you for this great plugin and your time :D
