### ISSUE TITLE
nimsuggest cannot be executed: Vim(let): E475 error

### ISSUE THREAD

**Issue by lf-araujo** [alaviss/nim.nvim#54]
Following up with what I mentioned at https://github.com/alaviss/nim.nvim/issues/42.  This error ocurrs whenever I save the file I am editing.

![image](https://user-images.githubusercontent.com/10139950/213920730-f46bd012-c678-414c-b9f7-c0ac7702389e.png)

More information on my system:

`:echo system(['nimsuggest', '-v'])`

Generates
```
E475: Invalid value for argument cmd: 'nimsuggest' is not executable
```

```
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/x86_64-solus-linux-gcc -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -fno-plt -Wall -Wno-error -Wp,-D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/build/YPKG/root/neovim/build/neovim-0.8.2/solusBuildDir/cmake.config -I/home/build/YPKG/root/neovim/build/neovim-0.8.2/src -I/usr/include -I/home/build/YPKG/root/neovim/build/neovim-0.8.2/solusBuildDir/src/nvim/auto -I/home/build/YPKG/root/neovim/build/neovim-0.8.2/solusBuildDir/include
Compiled by build@paddedroom

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

```
luis@solus ~ $ nimsuggest -v
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release -d:danger --gc:markAndSweep
```

**Comment by alaviss** [comment]
From the looks of it, `neovim` couldn't find `nimsuggest` in `PATH`. You can try `getenv("PATH")` to see if `nimsuggest` is in any of the folders referenced there.

If not, then your issue is just the missing `PATH` entry.

**Comment by lf-araujo** [comment]
Thanks, indeed it is not in the path, although I am setting it with:

```
vim.cmd([[


set path+=/usr/lib64/openjdk-11/bin/
set path+=/home/luis/.nimble/bin/nimsuggest
]])
```

- What am I doing wrong?

**Comment by alaviss** [comment]
From `:h path`

> ```
> 'path' 'pa'		string	(default on Unix: ".,/usr/include,,"
> 				   other systems: ".,,")
> 			global or local to buffer |global-local|
> 	This is a list of directories which will be searched when using the
> 	|gf|, [f, ]f, ^Wf, |:find|, |:sfind|, |:tabfind| and other commands,
> 	provided that the file being searched for has a relative path (not
> 	starting with "/", "./" or "../").  The directories in the 'path'
> 	option may be relative or absolute.
> ```

So this is for the built-in C header search and not the `PATH` for executables.

**Comment by lf-araujo** [comment]
Using alternative path setting also did not work:


```

vim.cmd([[

let $PATH.=':/usr/lib64/openjdk-11/bin/'
let $MYVIMRC='/home/luis/.nimble/bin/'

]])
```

I don't think this is a bug in your package, now. It must be something that changed in the last update of the nvim distribution I am using (Lunarvim). It used to work well before my last update, I will fiddle a little bit more, but I will close this.
