### ISSUE TITLE
Customizing Indent Level

### ISSUE THREAD

**Issue by eeriemyxi** [alaviss/nim.nvim#57]
Hi. When I turn this plugin on, it overwrites the indent level, which is globally 4 indent level, to 2 indent level.

I  am aware that 2 indent level is preferred by the official style guide. However, I do not wish to follow this style guide. Could you tell me how to reset the indent level to be 4?

**Comment by eeriemyxi** [comment]
I managed to resolve this issue by adding,
```lua
        vim.cmd [[
            autocmd FileType nim setlocal shiftwidth=4 softtabstop=4 expandtab
        ]]
```
On plugin initialization.

**Comment by alaviss** [comment]
You can set `g:nim_nep1` to `0` and it would also disable the automatic styling application.

This can be done with:

```lua
vim.g.nim_nep1 = 0
```
