### ISSUE TITLE
Primitive Types Don't Correctly Highlight

### ISSUE THREAD

**Issue by ifndefJOSH** [alaviss/nim.nvim#58]
According to [the latest Nim docs](https://nim-docs.readthedocs.io/en/latest/learn/nim_by_example/primitives/), Nim supports the following primitive types: `int`, `int8`, `int16`, `int32`, `int64` (and unsigned versions of all above), as well as `float`, `float32`, and `float64`. None of these are highlighted. There are two non-primitive types, `string` and `array`, which also do not appear to highlight.

Desired Behavior:
![image](https://github.com/user-attachments/assets/83cba41d-9e76-4392-9fff-449f921a5453)

Actual Behavior:
![image](https://github.com/user-attachments/assets/90d687b9-0ccb-4fe1-bf41-eee43735cf45)

**Comment by alaviss** [comment]
See https://github.com/alaviss/nim.nvim/pull/59#issuecomment-2377690132 for rationale behind this behavior.
