### ISSUE TITLE
[Question] Preview window

### ISSUE THREAD

**Issue by squattingmonk** [alaviss/nim.nvim#6]
The asciinema shows a preview window appearing as you move about the popup menu. However, I cannot get this to work. Is there a trick to making the preview window appear?

**Comment by matt-m95** [comment]
I think you mean [this](https://github.com/prabirshrestha/asyncomplete.vim#preview-window)

**Comment by squattingmonk** [comment]
Ah, okay. I had those options, but it still didn't work. Looks like it requires:
``` vim
let g:asyncomplete_auto_completeopt = 0
```
