### ISSUE TITLE
Please disable default folding

### ISSUE THREAD

**Issue by zevv** [alaviss/nim.nvim#9]
A bit surprised to find all my code folded. Better to disable unless explicitly enabled?

**Comment by alaviss** [comment]
Complain that to neovim, they have `foldenable` on by default :)

**Comment by dmeijboom** [comment]
The default of `foldenable` is not the issue here. You should never set the foldmethod to `indent` from a plugin. This is up to the user, not the vim plugin.

**Comment by alaviss** [comment]
> You should never set the foldmethod to indent from a plugin. This is up to the user, not the vim plugin.

And why is that? All I did was setting a fold type that'd work with the language by default. If you just don't want folding at all, then setting `nofoldenable` seems to be a no-brainer to me, it works no matter which plugin you use.

If you have your own `foldmethod` and you would like the plugin to not touch it at all, then I can re-add the toggle to not set `foldmethod`, but I can no longer change the default, as that would break existing setups. So far I haven't seen anyone with this use case, but I'd be happy to be proven wrong.

**Comment by dmeijboom** [comment]
> but I can no longer change the default, as that would break existing setups.

Well, I guess that makes sense but the `foldmethod` is basically the way to manage folding in neovim. I want folding to work but I want to do it manually not automatically. That's probably why folding is enabled by default (and foldmethod is set to manual) right?

**Comment by sschwarzer** [comment]
> That's probably why folding is enabled by default (and foldmethod is set to manual) right?

Isn't the foldmethod set to "manual" by default because this is a setting for all file types? I assume the reasoning here is that Neovim can't know the best foldmethod, so it falls back to one that should always work.

**Comment by trev-dev** [comment]
> > That's probably why folding is enabled by default (and foldmethod is set to manual) right?
> 
> Isn't the foldmethod set to "manual" by default because this is a setting for all file types? I assume the reasoning here is that Neovim can't know the best foldmethod, so it falls back to one that should always work.

Sorry for the necro, but yes.  The default fold method is manual, which makes it kinda peculiar how it gets changed for nim files and not other programming filetypes with this plugin.

It's my humble opinion that defaults not be changed unless explicitly set.

**Comment by DestyNova** [comment]
Just wanted to add that I also find the setting of `foldenable=indent` to be undesired.

I really like the plugin apart from that, so I've added the following to my vimrc as a workaround:

```vim
autocmd FileType nim setlocal foldmethod=manual
```
